version: '3.3'
services:
    radarr:
        container_name: radarr
        restart: unless-stopped
        volumes:
            - '/opt/radarr:/config'
            - '/mnt/video:/video'
            - '/opt/media/downloads/movies:/downloads/movies'
        environment:
            - TZ=Americas/Chicago
            - PUID=1000
            - PGID=1000
        ports:
            - '7878:7878'
        image: 'linuxserver/radarr:preview'

    sabnzbd:
        container_name: sabnzbd
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Americas/Chicago
        ports:
            - '8080:8080'
        volumes:
            - '/opt/sabnzbd:/config'
            - '/opt/media/downloads:/downloads'
            - '/opt/media/incomplete-downloads:/incomplete-downloads'
        restart: unless-stopped
        image: 'linuxserver/sabnzbd:latest'

    sonarr:
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        ports:
            - '8989:8989'
        volumes:
            - '/opt/sonarr:/config'
            - '/mnt/video:/video'
            - '/opt/media/downloads/tv:/downloads/tv'
        restart: unless-stopped
        image: 'linuxserver/sonarr:preview'

    tautulli:
        container_name: tautulli
        restart: unless-stopped
        volumes:
            - '/opt/tautulli:/config'
        environment:
            - PGID=100
            - PUID=1000
            - TZ=America/Chicago
        ports:
            - '8181:8181'
        image: linuxserver/tautulli:latest

    organizr-v2:
        container_name: organizr
        volumes:
            - '/opt/organizr:/config'
        environment:
            - TZ=Americas/Chicago
            - PGID=1000
            - PUID=1000
        restart: unless-stopped
        ports:
            - '4080:80'
        image: organizrtools/organizr-v2:latest
